use crate::config::AppConfig;
use crate::mapping::{GamepadState, ButtonMapping};
use crate::hidhide;
use serde::{Serialize, Deserialize};
use serde_big_array::BigArray;
use std::path::Path;

// Shared state between Controller Thread and GUI
#[derive(Clone, Serialize, Deserialize)]
pub struct SharedState {
    pub gamepad: GamepadState,
    pub status: String,
    pub device_name: String,
    pub connection_mode: String,
    #[serde(with = "BigArray")]
    pub raw_report: [u8; 80],
    pub last_update: u64,
    pub debug_active: bool,
    pub hide_controller: bool,
    pub hidhide_available: bool,
    pub vigembus_available: bool,
    pub virtual_pad_active: bool,
    pub hidden_device_id: Option<String>,
    pub mappings: Vec<ButtonMapping>,
    pub mappings_changed: bool,
    pub current_profile_name: String,
    pub deadzone_left: f32,
    pub deadzone_right: f32,
    pub mouse_sens_left: f32,
    pub mouse_sens_right: f32,
    pub mouse_sens_touchpad: f32,
    pub rgb_r: u8,
    pub rgb_g: u8,
    pub rgb_b: u8,
    pub rgb_brightness: u8,
    pub show_battery_led: bool,
    pub should_send_leds: bool,
    pub should_disconnect: bool,
    pub is_paused: bool,
    // Adaptive Triggers
    pub trigger_l2_mode: u8,      // 0=Off, 1=Rigid, 0x21=Section, 0x02=Pulse
    pub trigger_l2_start: u8,     // 0-255 (resistance start zone)
    pub trigger_l2_force: u8,     // 0-255 (resistance force)
    pub trigger_r2_mode: u8,
    pub trigger_r2_start: u8,
    pub trigger_r2_force: u8,
    pub should_send_triggers: bool,
    // Fuzzer State
    pub fuzzer_active: bool,
    pub fuzzer_log: String,
    pub fuzzer_step: usize,
    pub manual_report_id: u8,
    pub manual_flag_offset: usize,
    pub manual_rgb_offset: usize,
    pub manual_r: u8,
    pub manual_g: u8,
    pub manual_b: u8,
    pub last_write_status: String,
    pub should_send_manual: bool,
    pub bt_sequence: u8,
    pub crc_seed_idx: u8,
    pub disable_periodic: bool,
    pub sweep_active: bool,
    pub sweep_timeout_ms: u64,
    pub pinpoint_offset: usize,
    pub pinpoint_value: u8,
    pub device_path_str: String,
    pub should_send_pinpoint: bool,
    pub manual_player_led: u8,
    pub manual_pled_bright: u8,
    pub manual_pled_bright_off: usize,
    pub detected_devices_log: String,
    pub bt_flag_val: u8,
    pub bt_flag_val2: u8,
    pub manual_bt_len: usize,
    pub send_as_feature: bool,
    pub last_packet_hex: String,
    pub protocol_log: String,
    pub protocol_scan_active: bool,
    pub ui_visible: bool,
    pub start_minimized: bool,
    pub player_led_brightness: u8,
    pub should_exit: bool,
    pub should_reinit: bool,
}

impl SharedState {
    pub fn new(config: &AppConfig) -> Self {
        // Check ViGEmBus installation by file existence
        // This is more robust than trying to connect immediately at startup
        let vigem_installed = Path::new("C:\\Windows\\System32\\drivers\\ViGEmBus.sys").exists() ||
                              Path::new("C:\\Windows\\System32\\vigemclient.dll").exists();

        Self {
            gamepad: GamepadState::default(),
            status: "Waiting for controller...".to_string(),
            device_name: "None".to_string(),
            connection_mode: String::new(),
            raw_report: [0u8; 80],
            last_update: 0,
            debug_active: false,
            hide_controller: config.hide_controller,
            hidhide_available: hidhide::is_installed(),
            vigembus_available: vigem_installed,
            virtual_pad_active: false,
            hidden_device_id: None,
            mappings: config.mappings.clone(),
            mappings_changed: true,
            current_profile_name: config.active_profile.clone(),
            deadzone_left: config.deadzone_left,
            deadzone_right: config.deadzone_right,
            mouse_sens_left: config.mouse_sens_left,
            mouse_sens_right: config.mouse_sens_right,
            mouse_sens_touchpad: config.mouse_sens_touchpad,
            rgb_r: config.rgb_r,
            rgb_g: config.rgb_g,
            rgb_b: config.rgb_b,
            rgb_brightness: config.rgb_brightness,
            show_battery_led: config.show_battery_led,
            should_send_leds: false,
            should_disconnect: false,
            is_paused: false,
            // Adaptive Triggers
            trigger_l2_mode: config.trigger_l2_mode,
            trigger_l2_start: config.trigger_l2_start,
            trigger_l2_force: config.trigger_l2_force,
            trigger_r2_mode: config.trigger_r2_mode,
            trigger_r2_start: config.trigger_r2_start,
            trigger_r2_force: config.trigger_r2_force,
            should_send_triggers: false,
            fuzzer_active: false,
            fuzzer_log: "Ready to start fuzzing...".to_string(),
            fuzzer_step: 0,
            manual_report_id: 0x31,
            manual_flag_offset: 2,
            manual_rgb_offset: 46,
            manual_r: 255,
            manual_g: 0,
            manual_b: 0,
            last_write_status: "None".to_string(),
            should_send_manual: false,
            bt_sequence: 0,
            crc_seed_idx: 0,
            disable_periodic: false,
            sweep_active: false,
            sweep_timeout_ms: 250,
            pinpoint_offset: 46,
            pinpoint_value: 255,
            device_path_str: "Unknown".to_string(),
            should_send_pinpoint: false,
            manual_player_led: 0,
            manual_pled_bright: 0,
            manual_pled_bright_off: 44,
            detected_devices_log: "Scanning...".to_string(),
            bt_flag_val: 0xF7,
            bt_flag_val2: 0x15,
            manual_bt_len: 78,
            send_as_feature: false,
            last_packet_hex: String::new(),
            protocol_log: "Ready to scan.".to_string(),
            protocol_scan_active: false,
            ui_visible: !config.start_minimized,
            start_minimized: config.start_minimized,
            player_led_brightness: config.player_led_brightness,
            should_exit: false,
            should_reinit: false,
        }
    }
}
